const prices_arr = [
    {
        id: 1,
        price: 999,
        name: 'Silver',
        benefits: [
            "Counseling wise Eligibility Criteria",
            "State wise Counseling Details",
            "Institute wise Counseling Details",
            "Realtime Counselling Notifications",
            "Rank Predictor",
            "Branch wise Fee Structure",
            "Instititute wise Bond Details",
            "AIQ College Predictor",
        ]
    },
    {
        id: 2,
        price: 1999,
        name: 'Gold',
        benefits: [
            "Counseling wise Eligibility Criteria",
            "State wise Counseling Details",
            "Institute wise Counseling Details",
            "Realtime Counselling Notifications",
            "Rank Predictor",
            "Branch wise Fee Structure",
            "Instititute wise Bond Details",
            "AIQ College Predictor",
            "Deemed University Predictor",
            "DNB Institute Predictor",
            "State College Predictor",
            "Instititute wise Stipend Details",
        ]
    },
    {
        id: 3,
        price: 2499,
        name: 'Platinum',
        benefits: [
            "Counseling wise Eligibility Criteria",
            "State wise Counseling Details",
            "Institute wise Counseling Details",
            "Realtime Counselling Notifications",
            "Rank Predictor",
            "Branch wise Fee Structure",
            "Instititute wise Bond Details",
            "AIQ College Predictor",
            "Deemed University Predictor",
            "DNB Institute Predictor",
            "State College Predictor",
            "Instititute wise Stipend Details",
            "AIQ Choice Filling Assistance",
            "Deemed Choice Filling Assistance",
            "DNB Choice Filling Assistance",
            "State Choice Filling Assistance",
            "Closing Rank",
            "OPD, IPD, BEDs Details",
            "Cutoff Comparison",
            "Allotment Tracker",
        ]
    },
    {
        id: 4,
        price: 4999,
        name: 'Platinum Pro',
        popular:true,
        benefits: [
            "Counseling wise Eligibility Criteria",
            "State wise Counseling Details",
            "Institute wise Counseling Details",
            "Realtime Counselling Notifications",
            "Rank Predictor",
            "Branch wise Fee Structure",
            "Instititute wise Bond Details",
            "AIQ College Predictor",
            "Deemed University Predictor",
            "DNB Institute Predictor",
            "State College Predictor",
            "Instititute wise Stipend Details",
            "AIQ Choice Filling Assistance",
            "Deemed Choice Filling Assistance",
            "DNB Choice Filling Assistance",
            "State Choice Filling Assistance",
            "Closing Rank",
            "OPD, IPD, BEDs Details",
            "Cutoff Comparison",
            "Allotment Tracker",
            "Advance Profile Assessment",
            "Advance Assessment Report",
        ]
    },
    {
        id: 5,
        price: 24999,
        name: 'Personalised Counselling',
        benefits: [
            "Counseling wise Eligibility Criteria",
            "State wise Counseling Details",
            "Institute wise Counseling Details",
            "Realtime Counselling Notifications",
            "Rank Predictor",
            "Branch wise Fee Structure",
            "Instititute wise Bond Details",
            "AIQ College Predictor",
            "Deemed University Predictor",
            "DNB Institute Predictor",
            "State College Predictor",
            "Instititute wise Stipend Details",
            "AIQ Choice Filling Assistance",
            "Deemed Choice Filling Assistance",
            "DNB Choice Filling Assistance",
            "State Choice Filling Assistance",
            "Closing Rank",
            "OPD, IPD, BEDs Details",
            "Cutoff Comparison",
            "Allotment Tracker",
            "Advance Profile Assessment",
            "Advance Assessment Report",
        ]
    }
]


export {prices_arr}